name: CICD

on:
  push:
    branches: 
        - main

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            # Commands to execute on the remote server after logging in
            cd mango-piplines
            git pull origin main
            npm install
             # npx sequelize db:migrate
            pm2 restart index.js
